########################
## Cloud Build Config ##
########################

isEnabled: true
build:
  command: "npm install && npm run build"
  outputFolder: "build"
settings:
  type: website
  inSecure: true
