########################
## Cloud Build Config ##
########################

isEnabled: true
docker:
  preset: "npm"
  ignore: "node_modules"
build:
  command: "npm install && npm run build"
  outputFolder: "dist"
settings:
  isWebsite: true
  firestore: false
  inSecure: true